### ISSUE TITLE
Dúvidas sobre como contribuir para o projeto

### ISSUE THREAD

**Issue by KleversonNascimento** [LuanaFn/avas-denuncia-backend#2]
Oi, vi o[ site do projeto ](https://sites.google.com/view/plataforma-avas) e queria saber mais sobre como ele tem andado e como seria possível contribuir, pelo que eu vi no repositório a ideia é que ele seja em spring boot, você está fazendo/pretende fazer uma quebra melhor das tasks a nível de código? Pergunto isso porque não sei bem como você planeja o projeto e não sei quais as tasks seriam prioritárias agora, não sei quantas pessoas já estão participando do desenvolvimento e como vocês estão se organizando também.

Enfim, parabéns pela iniciativa.

┆Issue is synchronized with this [Trello card](https://trello.com/c/GytqTFX4) by [Unito](https://www.unito.io/learn-more)

**Comment by lurifn** [comment]
Oi Kleverson 

Eu estou controlando as tarefas através de um trello do projeto! Esse trello esta integrado com os issues do repo aqui do git, então por aqui você consegue acompanhar todas as tarefas pendentes... Mas se quiser oficializar seu envolvimento, fazer parte das reuniões de definições técnicas etc me avisa que eu te incluo :)
